id: I0B97B096
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:37:46+00:00'
last_modified: '2022-06-09T06:56:39.641415+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12627
  title: ཚད་མ་རིགས་གཏེར་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CF44:
      image_group_id: I1KG12641
      title: Volume 1 of tshad ma rigs gter rtsa 'grel/
      total_pages: 610
      order: 1
      base_file: CF44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
