id: I0B97B096
legacy_id: P007877
ocr_import_info:
  bdrc_scan_id: W1KG12627
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:34:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:34:52.826817+00:00'
last_modified: 2022-08-31 11:35:08.051691
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12627
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12627
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རིགས་གཏེར་རྩ་འགྲེལ།
  author: ས་སྐྱ་པཎྜི་ཏ་ཀུན་དགའ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.7157060456677522
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1KG12641:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12641
      total_pages: 610
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12641.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7157060456677522
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
