id: P007877
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12627
  title: ཚད་མ་རིགས་གཏེར་རྩ་འགྲེལ།
  author: ''
  volumes:
    d9fc37f200074f0fb67bb1a90b7715cf:
      image_group_id: I1KG12641
      title: ''
      volume_number: 1
      total_pages: 610
ebook_metadata:
  title: ཚད་མ་རིགས་གཏེར་རྩ་འགྲེལ།
  author: ''
  sku: P007877
  cover: cover.jpg
  layers:
  - pagination
