id: P007877
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:45.035306
source_metadata:
  id: bdr:W1KG12627
  title: ཚད་མ་རིགས་གཏེར་རྩ་འགྲེལ།
  author: ''
  volumes:
    1fd7b4e6c01e4f8ea735aeb23eb59ab1:
      image_group_id: I1KG12641
      title: Volume 1 of tshad ma rigs gter rtsa 'grel/
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
